# Generated by Django 4.1.3 on 2022-12-04 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100, verbose_name='book name')),
                ('book_author', models.CharField(max_length=100, verbose_name='book author')),
                ('description', models.TextField(verbose_name='description')),
                ('book_page', models.PositiveIntegerField(blank=True, verbose_name='number of book page')),
                ('status', models.CharField(choices=[('pub', 'published'), ('drf', 'draft')], max_length=3, verbose_name='status')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='time modified')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
        ),
    ]
