# Generated by Django 4.1.3 on 2022-12-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookblog',
            name='book_page',
            field=models.PositiveIntegerField(default=1, verbose_name='number of book page'),
            preserve_default=False,
        ),
    ]
