# Generated by Django 4.1.3 on 2022-12-02 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_blog', '0002_bookblog_book_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookblog',
            name='release_date',
        ),
    ]
