# Generated by Django 4.1.3 on 2023-01-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=1, max_length=11, verbose_name='phone number'),
            preserve_default=False,
        ),
    ]
