# Generated by Django 4.1.3 on 2022-12-11 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0004_subject_book_publisher_book_translator_book_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(default=1, max_length=50, verbose_name='publisher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book_store.subject', verbose_name='subject'),
            preserve_default=False,
        ),
    ]
