# Generated by Django 4.1.3 on 2022-12-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0006_alter_subject_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.PositiveIntegerField(default=1, verbose_name='publication year'),
            preserve_default=False,
        ),
    ]
