# Generated by Django 4.1.3 on 2022-12-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0007_book_publication_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='book_cover/', verbose_name='book_image'),
        ),
    ]
