# Generated by Django 4.1.3 on 2022-12-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0009_remove_book_image_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='book_cover/', verbose_name='book image'),
        ),
    ]
