# Generated by Django 4.1.3 on 2022-12-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0010_alter_book_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cover',
            new_name='image',
        ),
    ]
