# Generated by Django 4.1.3 on 2022-12-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0014_comment_delete_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.CharField(choices=[('1', 'Very Bad'), ('2', 'Bad'), ('3', 'Normal'), ('4', 'Good'), ('5', 'Perfect')], max_length=10, verbose_name='Your Score'),
        ),
    ]
