# Generated by Django 4.1.3 on 2022-12-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0016_alter_comment_active_alter_comment_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='recommend',
            field=models.BooleanField(default=True, verbose_name='i recommend this book'),
        ),
    ]
