# Generated by Django 4.1.3 on 2023-01-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0025_alter_book_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('book_name', 'book_author', 'translator', 'publisher')},
        ),
    ]
