# Generated by Django 4.1.3 on 2023-01-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0027_alter_book_unique_together_alter_book_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.CharField(max_length=100, verbose_name='book author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='translator'),
        ),
    ]
