# Generated by Django 4.1.3 on 2023-01-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0028_alter_book_book_author_alter_book_translator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=100, verbose_name='book name'),
        ),
    ]
