# Generated by Django 4.1.3 on 2023-01-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0029_alter_book_book_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('book_name', 'book_author', 'translator', 'publisher')},
        ),
    ]
